[package]
name = "dwbl-lib"
authors = ["Jeremy Ku-Benjet"]
version.workspace = true
edition.workspace = true
license.workspace = true

[lib]
crate-type = ["staticlib"]

[dependencies]
cxx.workspace = true

[build-dependencies]
cxx-build.workspace = true
